version: '3'
services:
  mydb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password
    ports:
      - 3306:3306
    volumes:
      - /home/sajacaros/workspace/study/docker/2st/01/my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/local/db_master:/var/lib/mysql
