version: '3'
services:
  myweb:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /home/dukim/workspace/study/docker/2st/02/nginx.conf:/etc/nginx/nginx.conf
    links:
      - mywas:tomcat
  mywas:
    image: tomcat
    ports: 
      - 8080:8080
